// Generated by scripts/generate-api-types.mjs from `pm api describe`. Do not edit by hand.
//
// Every action the pm contract publishes, as an input type. Regenerate with `npm run generate-api`
// after changing an action; the test in __tests__/pm-api.generated.test.ts fails when this file
// and the installed binary disagree.

import type { JsonValue, TaskRef } from "./pm-api";

export const API_CONTRACT_VERSION = "1.19.0";

/** Reveal the project's folder in Finder. */
export interface AppOpenInFinderInput {
  /** Project name or prefix. Defaults to the focused project. */
  project?: string;
}

/** Open the project's notes in Obsidian. */
export interface AppOpenInObsidianInput {
  /** Project name or prefix. Defaults to the focused project. */
  project?: string;
}

/** Put the page open in the front window's web card on its board as a new card, where it is. */
export type AppOpenPageAsNewCardInput = Record<string, never>;

/** Open the project's window in Folio. */
export interface AppOpenWindowInput {
  /** Project name or prefix. Defaults to the focused project. */
  project?: string;
}

/** Open Folio's settings. */
export type AppSettingsInput = Record<string, never>;

/** Show Folio's focus panel. */
export type AppShowPanelInput = Record<string, never>;

/** Read a typed capture line: its text, its due date, and the project it names. */
export interface CaptureParseInput {
  /** Today's date, YYYY-MM-DD. Defaults to today. */
  now?: string;
  /** A line as somebody would type it, e.g. "Email Dana due:friday @redesign". */
  text: string;
}

/** The pm configuration. */
export type ConfigGetInput = Record<string, never>;

/** Set one configuration key. */
export interface ConfigSetInput {
  /** Configuration key. */
  key: string;
  /** The new value. */
  value: JsonValue;
}

/** The focused project and its focused task. */
export type FocusGetInput = Record<string, never>;

/** Recent writes made through the contract, newest first. */
export interface JournalListInput {
  /** How many entries. Default 50. */
  limit?: number;
  /** Only this project's writes. */
  project?: string;
}

/** Reverse a write, if the file is still exactly as that write left it. */
export interface JournalUndoInput {
  /** Which entry, from journal.list. Default the most recent reversible one. */
  entry?: string;
  /** Only consider this project's writes. */
  project?: string;
}

/** Add a link to the project's links section. */
export interface NotesAddLinkInput {
  /** Link label. */
  label?: string;
  /** Project name or unambiguous prefix. */
  project: string;
  /** The URL. */
  text: string;
}

/** A project's notes, tasks, and focused task. */
export interface NotesGetInput {
  /** Project name or unambiguous prefix. */
  project: string;
}

/** Replace one of the project's detail sections. */
export interface NotesSetDetailInput {
  /** Which section. */
  key: "title" | "summary" | "problem" | "approach" | "goals" | "learnings";
  /** Project name or unambiguous prefix. */
  project: string;
  /** A string, or an array of strings for goals and learnings. */
  value: JsonValue;
}

/** Take an existing folder in the areas root on as an area, by writing notes into it. */
export interface ProjectAdoptInput {
  /** The folder's name, as `project.adoptable` lists it. */
  folder: string;
}

/** Folders in the areas root that could become areas but haven't yet. */
export type ProjectAdoptableInput = Record<string, never>;

/** Move a project or area to the archive. */
export interface ProjectArchiveInput {
  /** Project name or unambiguous prefix. */
  project: string;
}

/** Create a project, numbered within its domain, or an unnumbered area. */
export interface ProjectCreateInput {
  /** Domain code, e.g. W. Required for a project, refused for an area. */
  domain?: string;
  /** What to make. Default project. */
  kind?: "project" | "area";
  /** Project or area title. */
  title: string;
}

/** Make this the focused project. */
export interface ProjectFocusInput {
  /** Project name or unambiguous prefix. */
  project: string;
}

/** One project's paths and domain, its master and its members. */
export interface ProjectGetInput {
  /** Project name or unambiguous prefix. */
  project: string;
}

/** Every project and area, each with its kind. */
export interface ProjectListInput {
  /** Also read each project for what's happening in it: lastActivity (the later of its newest sitting's start and its notes' last write), its newest sitting and what it was about, how many tasks are open, and the soonest due. Sorted newest activity first. Default false. */
  activity?: boolean;
  /** Only this kind. Default both. */
  kind?: "project" | "area";
  /** Only these projects, by name, prefix or [[link]]. A master brings its members. */
  projects?: string[];
  /** Which folder to list. Default active. */
  scope?: "active" | "areas" | "archive" | "all";
}

/** Rename a project, keeping its domain and number. */
export interface ProjectRenameInput {
  /** Project name or unambiguous prefix. */
  project: string;
  /** The new title. */
  title: string;
}

/** Make a project part of a master project, or take it out. One level only. */
export interface ProjectSetPartOfInput {
  /** Take the project out of its master instead. */
  clearPartOf?: boolean;
  /** The master project or area, by name, code or prefix. */
  partOf?: string;
  /** Project name or unambiguous prefix. */
  project: string;
}

/** Move a project or area back out of the archive, to wherever its kind lives. */
export interface ProjectUnarchiveInput {
  /** Project name or unambiguous prefix. */
  project: string;
}

/** Give every session whose heading has no start time a best guess: the earliest thing the journal, done log or pick log recorded in it that day, else 9:00 AM. */
export interface SessionBackfillTimesInput {
  /** Project name or unambiguous prefix. */
  project: string;
}

/** Delete a session that has no tasks in it. */
export interface SessionDeleteInput {
  /** Project name or unambiguous prefix. */
  project: string;
  /** Session ISO date or index. */
  session: string;
  /** Digest of the label you read, to catch a session that has since changed. */
  sessionDigest?: string;
  /** Which session of that date. Default 0. */
  sessionOrdinal?: number;
}

/** The sittings in a period, across projects, in the order the day went: each with its prose, the tasks written and picked up in it, and what was finished or dropped while it was going on. Completions that fell in no sitting are listed apart, as elsewhere. */
export interface SessionListInput {
  /** Which span. Default today. */
  period?: "today" | "yesterday" | "week";
  /** Only these projects, by name, prefix or [[link]]. A master brings its members. Default every project. */
  projects?: string[];
  /** First day to include, YYYY-MM-DD. Overrides the period's start. */
  since?: string;
  /** Last day to include, YYYY-MM-DD. Overrides the period's end. */
  until?: string;
}

/** Append a note to the current session, starting one if needed. */
export interface SessionNoteInput {
  /** Project name or unambiguous prefix. */
  project: string;
  /** The note. */
  prose: string;
}

/** Change a session's label. Its date is preserved. */
export interface SessionRenameInput {
  /** The new label. */
  label: string;
  /** Project name or unambiguous prefix. */
  project: string;
  /** Session ISO date or index. */
  session: string;
  /** Digest of the label you read, to catch a session that has since changed. */
  sessionDigest?: string;
  /** Which session of that date. Default 0. */
  sessionOrdinal?: number;
}

/** Start a session, unless the current one is still open. */
export interface SessionStartInput {
  /** Optional label for the session. */
  label?: string;
  /** Start a new session even if the current one is still open. An empty one is still reused. */
  new?: boolean;
  /** Project name or unambiguous prefix. */
  project: string;
}

/** Add a task, to the current session or beside an existing task. */
export interface TaskAddInput {
  /** Insert relative to this task instead of appending to the current session. */
  anchor?: TaskRef;
  /** Due date, YYYY-MM-DD. */
  due?: string;
  /** Where the new task goes relative to the anchor. */
  position?: "before" | "after" | "child";
  /** Project name or unambiguous prefix. */
  project: string;
  /** The task's text. */
  text: string;
}

/** Complete a task, or several, along with their subtrees. */
export interface TaskCompleteInput {
  /** Move focus onward afterwards. Default true. */
  advanceFocus?: boolean;
  /** Project name or unambiguous prefix. */
  project: string;
  /** The `revision` from the read this came from. When given, the write happens only if the document is still that one. */
  revision?: string;
  /** The task to act on. Give this or `tasks`, not both. */
  task?: TaskRef;
  /** Several tasks, acted on in one write. Give this or `task`, not both. */
  tasks?: TaskRef[];
}

/** Delete a task, or several, along with their subtrees. */
export interface TaskDeleteInput {
  /** Project name or unambiguous prefix. */
  project: string;
  /** The `revision` from the read this came from. When given, the write happens only if the document is still that one. */
  revision?: string;
  /** The task to act on. Give this or `tasks`, not both. */
  task?: TaskRef;
  /** Several tasks, acted on in one write. Give this or `task`, not both. */
  tasks?: TaskRef[];
}

/** Move focus to the first open leaf under the focused task. */
export interface TaskDiveInInput {
  /** Project name or unambiguous prefix. */
  project: string;
}

/** What got done: tasks completed in a period, across every project, newest first. */
export interface TaskDoneInput {
  /** Also list tasks dropped in the period, marked. Default false. */
  includeDropped?: boolean;
  /** Which span. Default today. */
  period?: "today" | "week";
  /** Which projects to look in. Default all. */
  scope?: "active" | "archive" | "all";
  /** First day to include, YYYY-MM-DD. Overrides the period's start. */
  since?: string;
  /** Last day to include, YYYY-MM-DD. Overrides the period's end. */
  until?: string;
}

/** Drop a task, or several, along with their open subtasks: close them without their being done. */
export interface TaskDropInput {
  /** Move focus onward afterwards. Default true. */
  advanceFocus?: boolean;
  /** Project name or unambiguous prefix. */
  project: string;
  /** The `revision` from the read this came from. When given, the write happens only if the document is still that one. */
  revision?: string;
  /** The task to act on. Give this or `tasks`, not both. */
  task?: TaskRef;
  /** Several tasks, acted on in one write. Give this or `task`, not both. */
  tasks?: TaskRef[];
}

/** Open tasks due by a date, across projects, soonest first and overdue first of all. A line is listed when it says a date itself, not when it inherits one. */
export interface TaskDueInput {
  /** Only these projects, by name, prefix or [[link]]. A master brings its members. Default every active project and area. */
  projects?: string[];
  /** How far ahead: today, week (the next seven days, the default), or through a day given as YYYY-MM-DD. */
  until?: string;
}

/** Make this the project's focused task. A task from an older session is picked up into the current one as well, unless pick is false. */
export interface TaskFocusInput {
  /** Pick the task up into the current session when it's from an older one. Default true. */
  pick?: boolean;
  /** Project name or unambiguous prefix. */
  project: string;
  /** The task to act on. */
  task: TaskRef;
}

/** Open tasks left in older sittings, across projects: grouped by project and then by sitting, oldest first, each sitting with what it was about and each task with its last pick-up. */
export interface TaskLeftoversInput {
  /** How old a sitting has to be: before today (the default), before yesterday, before this week, or before a day given as YYYY-MM-DD. */
  before?: string;
  /** Only these projects, by name, prefix or [[link]]. A master brings its members. Default every active project and area. */
  projects?: string[];
}

/** A project's tasks, each with the reference needed to act on it. */
export interface TaskListInput {
  /** Include completed and dropped tasks. Default false. */
  includeCompleted?: boolean;
  /** Cap the number returned. */
  limit?: number;
  /** Project name or prefix. Defaults to the focused project. */
  project?: string;
}

/** Pick up a task from an older session into the current one, or several. The task isn't moved: it stays where it was written, and the current session shows it as picked up. */
export interface TaskPickInput {
  /** Project name or unambiguous prefix. */
  project: string;
  /** The `revision` from the read this came from. When given, the write happens only if the document is still that one. */
  revision?: string;
  /** The task to act on. Give this or `tasks`, not both. */
  task?: TaskRef;
  /** Several tasks, acted on in one write. Give this or `task`, not both. */
  tasks?: TaskRef[];
}

/** How many of a project's tasks are done. Dropped tasks are left out of the total. */
export interface TaskProgressInput {
  /** Project name or prefix. Defaults to the focused project. */
  project?: string;
}

/** Put back a picked-up task, or several: take it out of the session it was picked up into. The task itself isn't touched. */
export interface TaskReleaseInput {
  /** Project name or unambiguous prefix. */
  project: string;
  /** The `revision` from the read this came from. When given, the write happens only if the document is still that one. */
  revision?: string;
  /** The ISO date of the session it was picked up into. Default: its latest pick. */
  session?: string;
  /** Digest of that session's label, to catch a session that has since changed. */
  sessionDigest?: string;
  /** Which session of that date. Default 0. */
  sessionOrdinal?: number;
  /** The task to act on. Give this or `tasks`, not both. */
  task?: TaskRef;
  /** Several tasks, acted on in one write. Give this or `task`, not both. */
  tasks?: TaskRef[];
}

/** Re-open a completed or dropped task, or several, and put focus back. */
export interface TaskReopenInput {
  /** Project name or unambiguous prefix. */
  project: string;
  /** The `revision` from the read this came from. When given, the write happens only if the document is still that one. */
  revision?: string;
  /** The task to act on. Give this or `tasks`, not both. */
  task?: TaskRef;
  /** Several tasks, acted on in one write. Give this or `task`, not both. */
  tasks?: TaskRef[];
}

/** Find open tasks across every project by the words in them. */
export interface TaskSearchInput {
  /** How many to return. Default 20. */
  limit?: number;
  /** Break ties toward this project. Defaults to the focused one. */
  project?: string;
  /** Only these projects' tasks, by name, prefix or [[link]]. A master brings its members. Default every project. */
  projects?: string[];
  /** Words to look for, in any order. */
  query: string;
  /** Which projects to search. Default all. */
  scope?: "active" | "archive" | "all";
}

/** Set or clear the due date on a task, or on several. */
export interface TaskSetDueInput {
  /** Remove the due date instead of setting one. */
  clearDue?: boolean;
  /** Due date, YYYY-MM-DD. */
  due?: string;
  /** Project name or unambiguous prefix. */
  project: string;
  /** The `revision` from the read this came from. When given, the write happens only if the document is still that one. */
  revision?: string;
  /** The task to act on. Give this or `tasks`, not both. */
  task?: TaskRef;
  /** Several tasks, acted on in one write. Give this or `task`, not both. */
  tasks?: TaskRef[];
}

/** Rename a task in place, or several, each to its own new text. */
export interface TaskSetTextInput {
  /** Project name or unambiguous prefix. */
  project: string;
  /** The `revision` from the read this came from. When given, the write happens only if the document is still that one. */
  revision?: string;
  /** The task to act on. Give this or `tasks`, not both. */
  task?: TaskRef;
  /** Several tasks to rename in one write, each with its own `text`. Give this or `task` with `text`, not both. */
  tasks?: (TaskRef & { text: string })[];
  /** The new text, with `task`. */
  text?: string;
}

/** Set or clear what a task is waiting on, or do it to several. */
export interface TaskSetWaitingInput {
  /** Remove the wait instead of setting one. */
  clearWaiting?: boolean;
  /** Project name or unambiguous prefix. */
  project: string;
  /** The `revision` from the read this came from. When given, the write happens only if the document is still that one. */
  revision?: string;
  /** The task to act on. Give this or `tasks`, not both. */
  task?: TaskRef;
  /** Several tasks, acted on in one write. Give this or `task`, not both. */
  tasks?: TaskRef[];
  /** What it's waiting on: a project, an area, or a person's name. */
  waiting?: string;
}

/** Dissolve a parent task, promoting its children. */
export interface TaskUnwrapInput {
  /** Project name or unambiguous prefix. */
  project: string;
  /** The task to act on. */
  task: TaskRef;
}

/** Everything you're waiting on, grouped by what it's waiting on. */
export interface TaskWaitingInput {
  /** Only these projects' tasks, by name, prefix or [[link]]. A master brings its members. What they wait on can be anywhere. Default every project. */
  projects?: string[];
  /** Which projects to look in. Default active. */
  scope?: "active" | "archive" | "all";
}

/** Open tasks with a due date, soonest first. */
export interface TaskWhatsDueInput {
  /** Cap the number returned. */
  limit?: number;
  /** Project name or prefix. Defaults to the focused project. */
  project?: string;
}

/** Wrap a task and its subtree in a new parent task. */
export interface TaskWrapInput {
  /** Project name or unambiguous prefix. */
  project: string;
  /** The task to act on. */
  task: TaskRef;
  /** The new parent's text. */
  text: string;
}

/** Every action, mapped to the input it takes. */
export interface ApiInputs {
  "app.openInFinder": AppOpenInFinderInput;
  "app.openInObsidian": AppOpenInObsidianInput;
  "app.openPageAsNewCard": AppOpenPageAsNewCardInput;
  "app.openWindow": AppOpenWindowInput;
  "app.settings": AppSettingsInput;
  "app.showPanel": AppShowPanelInput;
  "capture.parse": CaptureParseInput;
  "config.get": ConfigGetInput;
  "config.set": ConfigSetInput;
  "focus.get": FocusGetInput;
  "journal.list": JournalListInput;
  "journal.undo": JournalUndoInput;
  "notes.addLink": NotesAddLinkInput;
  "notes.get": NotesGetInput;
  "notes.setDetail": NotesSetDetailInput;
  "project.adopt": ProjectAdoptInput;
  "project.adoptable": ProjectAdoptableInput;
  "project.archive": ProjectArchiveInput;
  "project.create": ProjectCreateInput;
  "project.focus": ProjectFocusInput;
  "project.get": ProjectGetInput;
  "project.list": ProjectListInput;
  "project.rename": ProjectRenameInput;
  "project.setPartOf": ProjectSetPartOfInput;
  "project.unarchive": ProjectUnarchiveInput;
  "session.backfillTimes": SessionBackfillTimesInput;
  "session.delete": SessionDeleteInput;
  "session.list": SessionListInput;
  "session.note": SessionNoteInput;
  "session.rename": SessionRenameInput;
  "session.start": SessionStartInput;
  "task.add": TaskAddInput;
  "task.complete": TaskCompleteInput;
  "task.delete": TaskDeleteInput;
  "task.diveIn": TaskDiveInInput;
  "task.done": TaskDoneInput;
  "task.drop": TaskDropInput;
  "task.due": TaskDueInput;
  "task.focus": TaskFocusInput;
  "task.leftovers": TaskLeftoversInput;
  "task.list": TaskListInput;
  "task.pick": TaskPickInput;
  "task.progress": TaskProgressInput;
  "task.release": TaskReleaseInput;
  "task.reopen": TaskReopenInput;
  "task.search": TaskSearchInput;
  "task.setDue": TaskSetDueInput;
  "task.setText": TaskSetTextInput;
  "task.setWaiting": TaskSetWaitingInput;
  "task.unwrap": TaskUnwrapInput;
  "task.waiting": TaskWaitingInput;
  "task.whatsDue": TaskWhatsDueInput;
  "task.wrap": TaskWrapInput;
}

export type ApiActionName = keyof ApiInputs;

/** Which tier each action belongs to, so a caller can tell a read from a write. */
export const API_TIERS: Record<
  ApiActionName,
  "mutation" | "query" | "affordance"
> = {
  "app.openInFinder": "affordance",
  "app.openInObsidian": "affordance",
  "app.openPageAsNewCard": "affordance",
  "app.openWindow": "affordance",
  "app.settings": "affordance",
  "app.showPanel": "affordance",
  "capture.parse": "query",
  "config.get": "query",
  "config.set": "mutation",
  "focus.get": "query",
  "journal.list": "query",
  "journal.undo": "mutation",
  "notes.addLink": "mutation",
  "notes.get": "query",
  "notes.setDetail": "mutation",
  "project.adopt": "mutation",
  "project.adoptable": "query",
  "project.archive": "mutation",
  "project.create": "mutation",
  "project.focus": "mutation",
  "project.get": "query",
  "project.list": "query",
  "project.rename": "mutation",
  "project.setPartOf": "mutation",
  "project.unarchive": "mutation",
  "session.backfillTimes": "mutation",
  "session.delete": "mutation",
  "session.list": "query",
  "session.note": "mutation",
  "session.rename": "mutation",
  "session.start": "mutation",
  "task.add": "mutation",
  "task.complete": "mutation",
  "task.delete": "mutation",
  "task.diveIn": "mutation",
  "task.done": "query",
  "task.drop": "mutation",
  "task.due": "query",
  "task.focus": "mutation",
  "task.leftovers": "query",
  "task.list": "query",
  "task.pick": "mutation",
  "task.progress": "query",
  "task.release": "mutation",
  "task.reopen": "mutation",
  "task.search": "query",
  "task.setDue": "mutation",
  "task.setText": "mutation",
  "task.setWaiting": "mutation",
  "task.unwrap": "mutation",
  "task.waiting": "query",
  "task.whatsDue": "query",
  "task.wrap": "mutation",
};
