// Generated by scripts/generate-api-types.mjs from `pm api describe`. Do not edit by hand.
//
// Every action the pm contract publishes, as an input type. Regenerate with `npm run generate-api`
// after changing an action; the test in __tests__/pm-api.generated.test.ts fails when this file
// and the installed binary disagree.

import type { JsonValue, TaskRef } from "./pm-api";

export const API_CONTRACT_VERSION = "1.0.0";

/** Reveal the project's folder in Finder. */
export interface AppOpenInFinderInput {
  /** Project name or prefix. Defaults to the focused project. */
  project?: string;
}

/** Open the project's notes in Obsidian. */
export interface AppOpenInObsidianInput {
  /** Project name or prefix. Defaults to the focused project. */
  project?: string;
}

/** Open the project's window in PM. */
export interface AppOpenWindowInput {
  /** Project name or prefix. Defaults to the focused project. */
  project?: string;
}

/** Open PM's settings. */
export type AppSettingsInput = Record<string, never>;

/** Show PM's focus panel. */
export type AppShowPanelInput = Record<string, never>;

/** The pm configuration. */
export type ConfigGetInput = Record<string, never>;

/** Set one configuration key. */
export interface ConfigSetInput {
  /** Configuration key. */
  key: string;
  /** The new value. */
  value: JsonValue;
}

/** The focused project and its focused task. */
export type FocusGetInput = Record<string, never>;

/** Recent writes made through the contract, newest first. */
export interface JournalListInput {
  /** How many entries. Default 50. */
  limit?: number;
  /** Only this project's writes. */
  project?: string;
}

/** Reverse a write, if the file is still exactly as that write left it. */
export interface JournalUndoInput {
  /** Which entry, from journal.list. Default the most recent reversible one. */
  entry?: string;
  /** Only consider this project's writes. */
  project?: string;
}

/** Add a link to the project's links section. */
export interface NotesAddLinkInput {
  /** Link label. */
  label?: string;
  /** Project name or unambiguous prefix. */
  project: string;
  /** The URL. */
  text: string;
}

/** A project's notes, tasks, and focused task. */
export interface NotesGetInput {
  /** Project name or unambiguous prefix. */
  project: string;
}

/** Replace one of the project's detail sections. */
export interface NotesSetDetailInput {
  /** Which section. */
  key: "title" | "summary" | "problem" | "approach" | "goals" | "learnings";
  /** Project name or unambiguous prefix. */
  project: string;
  /** A string, or an array of strings for goals and learnings. */
  value: JsonValue;
}

/** Move a project to the archive. */
export interface ProjectArchiveInput {
  /** Project name or unambiguous prefix. */
  project: string;
}

/** Create a project, numbered within its domain. */
export interface ProjectCreateInput {
  /** Domain code, e.g. W. */
  domain: string;
  /** Project title. */
  title: string;
}

/** Make this the focused project. */
export interface ProjectFocusInput {
  /** Project name or unambiguous prefix. */
  project: string;
}

/** One project's paths and domain. */
export interface ProjectGetInput {
  /** Project name or unambiguous prefix. */
  project: string;
}

/** Every project, with its domain. */
export interface ProjectListInput {
  /** Which folder to list. Default active. */
  scope?: "active" | "archive" | "all";
}

/** Rename a project, keeping its domain and number. */
export interface ProjectRenameInput {
  /** Project name or unambiguous prefix. */
  project: string;
  /** The new title. */
  title: string;
}

/** Move a project back to active. */
export interface ProjectUnarchiveInput {
  /** Project name or unambiguous prefix. */
  project: string;
}

/** Delete a session that has no tasks in it. */
export interface SessionDeleteInput {
  /** Project name or unambiguous prefix. */
  project: string;
  /** Session ISO date or index. */
  session: string;
  /** Which session of that date. Default 0. */
  sessionOrdinal?: number;
}

/** Append a note to today's session, creating it if needed. */
export interface SessionNoteInput {
  /** Project name or unambiguous prefix. */
  project: string;
  /** The note. */
  prose: string;
}

/** Change a session's label. Its date is preserved. */
export interface SessionRenameInput {
  /** The new label. */
  label: string;
  /** Project name or unambiguous prefix. */
  project: string;
  /** Session ISO date or index. */
  session: string;
  /** Which session of that date. Default 0. */
  sessionOrdinal?: number;
}

/** Start today's session, if there isn't one. */
export interface SessionStartInput {
  /** Optional label for the session. */
  label?: string;
  /** Project name or unambiguous prefix. */
  project: string;
}

/** Add a task, to today's session or beside an existing task. */
export interface TaskAddInput {
  /** Insert relative to this task instead of appending to today. */
  anchor?: TaskRef;
  /** Due date, YYYY-MM-DD. */
  due?: string;
  /** Where the new task goes relative to the anchor. */
  position?: "before" | "after" | "child";
  /** Project name or unambiguous prefix. */
  project: string;
  /** The task's text. */
  text: string;
}

/** Complete a task, or several, along with their subtrees. */
export interface TaskCompleteInput {
  /** Move focus onward afterwards. Default true. */
  advanceFocus?: boolean;
  /** Project name or unambiguous prefix. */
  project: string;
  /** The `revision` from the read this came from. When given, the write happens only if the document is still that one. */
  revision?: string;
  /** The task to act on. Give this or `tasks`, not both. */
  task?: TaskRef;
  /** Several tasks, acted on in one write. Give this or `task`, not both. */
  tasks?: TaskRef[];
}

/** Delete a task, or several, along with their subtrees. */
export interface TaskDeleteInput {
  /** Project name or unambiguous prefix. */
  project: string;
  /** The `revision` from the read this came from. When given, the write happens only if the document is still that one. */
  revision?: string;
  /** The task to act on. Give this or `tasks`, not both. */
  task?: TaskRef;
  /** Several tasks, acted on in one write. Give this or `task`, not both. */
  tasks?: TaskRef[];
}

/** Move focus to the first open leaf under the focused task. */
export interface TaskDiveInInput {
  /** Project name or unambiguous prefix. */
  project: string;
}

/** Make this the project's focused task. */
export interface TaskFocusInput {
  /** Project name or unambiguous prefix. */
  project: string;
  /** The task to act on. */
  task: TaskRef;
}

/** A project's tasks, each with the reference needed to act on it. */
export interface TaskListInput {
  /** Include completed tasks. Default false. */
  includeCompleted?: boolean;
  /** Cap the number returned. */
  limit?: number;
  /** Project name or prefix. Defaults to the focused project. */
  project?: string;
}

/** How many of a project's tasks are done. */
export interface TaskProgressInput {
  /** Project name or prefix. Defaults to the focused project. */
  project?: string;
}

/** Re-open a completed task, or several, and put focus back. */
export interface TaskReopenInput {
  /** Project name or unambiguous prefix. */
  project: string;
  /** The `revision` from the read this came from. When given, the write happens only if the document is still that one. */
  revision?: string;
  /** The task to act on. Give this or `tasks`, not both. */
  task?: TaskRef;
  /** Several tasks, acted on in one write. Give this or `task`, not both. */
  tasks?: TaskRef[];
}

/** Set or clear the due date on a task, or on several. */
export interface TaskSetDueInput {
  /** Remove the due date instead of setting one. */
  clearDue?: boolean;
  /** Due date, YYYY-MM-DD. */
  due?: string;
  /** Project name or unambiguous prefix. */
  project: string;
  /** The `revision` from the read this came from. When given, the write happens only if the document is still that one. */
  revision?: string;
  /** The task to act on. Give this or `tasks`, not both. */
  task?: TaskRef;
  /** Several tasks, acted on in one write. Give this or `task`, not both. */
  tasks?: TaskRef[];
}

/** Rename a task in place. */
export interface TaskSetTextInput {
  /** Project name or unambiguous prefix. */
  project: string;
  /** The task to act on. */
  task: TaskRef;
  /** The new text. */
  text: string;
}

/** Dissolve a parent task, promoting its children. */
export interface TaskUnwrapInput {
  /** Project name or unambiguous prefix. */
  project: string;
  /** The task to act on. */
  task: TaskRef;
}

/** Open tasks with a due date, soonest first. */
export interface TaskWhatsDueInput {
  /** Cap the number returned. */
  limit?: number;
  /** Project name or prefix. Defaults to the focused project. */
  project?: string;
}

/** Wrap a task and its subtree in a new parent task. */
export interface TaskWrapInput {
  /** Project name or unambiguous prefix. */
  project: string;
  /** The task to act on. */
  task: TaskRef;
  /** The new parent's text. */
  text: string;
}

/** Every action, mapped to the input it takes. */
export interface ApiInputs {
  "app.openInFinder": AppOpenInFinderInput;
  "app.openInObsidian": AppOpenInObsidianInput;
  "app.openWindow": AppOpenWindowInput;
  "app.settings": AppSettingsInput;
  "app.showPanel": AppShowPanelInput;
  "config.get": ConfigGetInput;
  "config.set": ConfigSetInput;
  "focus.get": FocusGetInput;
  "journal.list": JournalListInput;
  "journal.undo": JournalUndoInput;
  "notes.addLink": NotesAddLinkInput;
  "notes.get": NotesGetInput;
  "notes.setDetail": NotesSetDetailInput;
  "project.archive": ProjectArchiveInput;
  "project.create": ProjectCreateInput;
  "project.focus": ProjectFocusInput;
  "project.get": ProjectGetInput;
  "project.list": ProjectListInput;
  "project.rename": ProjectRenameInput;
  "project.unarchive": ProjectUnarchiveInput;
  "session.delete": SessionDeleteInput;
  "session.note": SessionNoteInput;
  "session.rename": SessionRenameInput;
  "session.start": SessionStartInput;
  "task.add": TaskAddInput;
  "task.complete": TaskCompleteInput;
  "task.delete": TaskDeleteInput;
  "task.diveIn": TaskDiveInInput;
  "task.focus": TaskFocusInput;
  "task.list": TaskListInput;
  "task.progress": TaskProgressInput;
  "task.reopen": TaskReopenInput;
  "task.setDue": TaskSetDueInput;
  "task.setText": TaskSetTextInput;
  "task.unwrap": TaskUnwrapInput;
  "task.whatsDue": TaskWhatsDueInput;
  "task.wrap": TaskWrapInput;
}

export type ApiActionName = keyof ApiInputs;

/** Which tier each action belongs to, so a caller can tell a read from a write. */
export const API_TIERS: Record<
  ApiActionName,
  "mutation" | "query" | "affordance"
> = {
  "app.openInFinder": "affordance",
  "app.openInObsidian": "affordance",
  "app.openWindow": "affordance",
  "app.settings": "affordance",
  "app.showPanel": "affordance",
  "config.get": "query",
  "config.set": "mutation",
  "focus.get": "query",
  "journal.list": "query",
  "journal.undo": "mutation",
  "notes.addLink": "mutation",
  "notes.get": "query",
  "notes.setDetail": "mutation",
  "project.archive": "mutation",
  "project.create": "mutation",
  "project.focus": "mutation",
  "project.get": "query",
  "project.list": "query",
  "project.rename": "mutation",
  "project.unarchive": "mutation",
  "session.delete": "mutation",
  "session.note": "mutation",
  "session.rename": "mutation",
  "session.start": "mutation",
  "task.add": "mutation",
  "task.complete": "mutation",
  "task.delete": "mutation",
  "task.diveIn": "mutation",
  "task.focus": "mutation",
  "task.list": "query",
  "task.progress": "query",
  "task.reopen": "mutation",
  "task.setDue": "mutation",
  "task.setText": "mutation",
  "task.unwrap": "mutation",
  "task.whatsDue": "query",
  "task.wrap": "mutation",
};
