// Generated by pm-mac/scripts/generate-api-actions.mjs from `pm api describe`. Do not edit by hand.
//
// Every action the pm contract publishes, as a case. Regenerate with
//     node pm-mac/scripts/generate-api-actions.mjs
// after changing an action; PMActionsTests fails when this file and the binary disagree.

import PmLib

/// The contract version this file was generated from.
///
/// Named distinctly from PmLib's own `apiContractVersion`, which is in scope here — a file-scope
/// `let` of the same name would shadow it silently, and a check comparing the two would then be
/// comparing a thing with itself.
let generatedFromContractVersion = "1.11.0"

/// Every action the contract publishes.
///
/// The point of the enum is that `PMContract.perform(.taskSetDue, …)` cannot be misspelled, where
/// `PMContract.perform("task.setDeu", …)` compiled and threw at runtime. The raw value is the wire
/// name, so nothing has to be translated at the boundary.
enum PMAction: String, CaseIterable, Sendable {
    /// Reveal the project's folder in Finder.
    case appOpenInFinder = "app.openInFinder"
    /// Open the project's notes in Obsidian.
    case appOpenInObsidian = "app.openInObsidian"
    /// Put the page open in the front window's web card on its board as a new card, where it is.
    case appOpenPageAsNewCard = "app.openPageAsNewCard"
    /// Open the project's window in Folio.
    case appOpenWindow = "app.openWindow"
    /// Open Folio's settings.
    case appSettings = "app.settings"
    /// Show Folio's focus panel.
    case appShowPanel = "app.showPanel"
    /// Read a typed capture line: its text, its due date, and the project it names.
    case captureParse = "capture.parse"
    /// The pm configuration.
    case configGet = "config.get"
    /// Set one configuration key.
    case configSet = "config.set"
    /// The focused project and its focused task.
    case focusGet = "focus.get"
    /// Recent writes made through the contract, newest first.
    case journalList = "journal.list"
    /// Reverse a write, if the file is still exactly as that write left it.
    case journalUndo = "journal.undo"
    /// Add a link to the project's links section.
    case notesAddLink = "notes.addLink"
    /// A project's notes, tasks, and focused task.
    case notesGet = "notes.get"
    /// Replace one of the project's detail sections.
    case notesSetDetail = "notes.setDetail"
    /// Take an existing folder in the areas root on as an area, by writing notes into it.
    case projectAdopt = "project.adopt"
    /// Folders in the areas root that could become areas but haven't yet.
    case projectAdoptable = "project.adoptable"
    /// Move a project or area to the archive.
    case projectArchive = "project.archive"
    /// Create a project, numbered within its domain, or an unnumbered area.
    case projectCreate = "project.create"
    /// Make this the focused project.
    case projectFocus = "project.focus"
    /// One project's paths and domain, its master and its members.
    case projectGet = "project.get"
    /// Every project and area, each with its kind.
    case projectList = "project.list"
    /// Rename a project, keeping its domain and number.
    case projectRename = "project.rename"
    /// Make a project part of a master project, or take it out. One level only.
    case projectSetPartOf = "project.setPartOf"
    /// Move a project or area back out of the archive, to wherever its kind lives.
    case projectUnarchive = "project.unarchive"
    /// Delete a session that has no tasks in it.
    case sessionDelete = "session.delete"
    /// Append a note to the current session, starting one if needed.
    case sessionNote = "session.note"
    /// Change a session's label. Its date is preserved.
    case sessionRename = "session.rename"
    /// Start a session, unless the current one is still open.
    case sessionStart = "session.start"
    /// Add a task, to the current session or beside an existing task.
    case taskAdd = "task.add"
    /// Complete a task, or several, along with their subtrees.
    case taskComplete = "task.complete"
    /// Delete a task, or several, along with their subtrees.
    case taskDelete = "task.delete"
    /// Move focus to the first open leaf under the focused task.
    case taskDiveIn = "task.diveIn"
    /// What got done: tasks completed in a period, across every project, newest first.
    case taskDone = "task.done"
    /// Drop a task, or several, along with their open subtasks: close them without their being done.
    case taskDrop = "task.drop"
    /// Make this the project's focused task.
    case taskFocus = "task.focus"
    /// A project's tasks, each with the reference needed to act on it.
    case taskList = "task.list"
    /// How many of a project's tasks are done. Dropped tasks are left out of the total.
    case taskProgress = "task.progress"
    /// Re-open a completed or dropped task, or several, and put focus back.
    case taskReopen = "task.reopen"
    /// Find open tasks across every project by the words in them.
    case taskSearch = "task.search"
    /// Set or clear the due date on a task, or on several.
    case taskSetDue = "task.setDue"
    /// Rename a task in place.
    case taskSetText = "task.setText"
    /// Set or clear what a task is waiting on, or do it to several.
    case taskSetWaiting = "task.setWaiting"
    /// Dissolve a parent task, promoting its children.
    case taskUnwrap = "task.unwrap"
    /// Everything you're waiting on, grouped by what it's waiting on.
    case taskWaiting = "task.waiting"
    /// Open tasks with a due date, soonest first.
    case taskWhatsDue = "task.whatsDue"
    /// Wrap a task and its subtree in a new parent task.
    case taskWrap = "task.wrap"

    /// Which tier this belongs to, so a caller can tell a read from a write — and so the
    /// in-process adapter can refuse to send an affordance to the dispatcher.
    var tier: ApiTier {
        switch self {
        case .configSet, .journalUndo, .notesAddLink, .notesSetDetail, .projectAdopt, .projectArchive, .projectCreate, .projectFocus, .projectRename, .projectSetPartOf, .projectUnarchive, .sessionDelete, .sessionNote, .sessionRename, .sessionStart, .taskAdd, .taskComplete, .taskDelete, .taskDiveIn, .taskDrop, .taskFocus, .taskReopen, .taskSetDue, .taskSetText, .taskSetWaiting, .taskUnwrap, .taskWrap:
            return .mutation
        case .captureParse, .configGet, .focusGet, .journalList, .notesGet, .projectAdoptable, .projectGet, .projectList, .taskDone, .taskList, .taskProgress, .taskSearch, .taskWaiting, .taskWhatsDue:
            return .query
        case .appOpenInFinder, .appOpenInObsidian, .appOpenPageAsNewCard, .appOpenWindow, .appSettings, .appShowPanel:
            return .affordance
        }
    }

    /// The fields this action will not run without.
    ///
    /// `ApiInput` is one struct of twenty-nine optional fields serving every action, so a
    /// caller that forgets one is only told when the dispatcher refuses it. Published here so
    /// a debug build can say so at the call site instead — see `PMContract.perform`.
    var requiredFields: [String] {
        switch self {
        case .appOpenInFinder, .appOpenInObsidian, .appOpenPageAsNewCard, .appOpenWindow, .appSettings, .appShowPanel, .configGet, .focusGet, .journalList, .journalUndo, .projectAdoptable, .projectList, .taskDone, .taskList, .taskProgress, .taskWaiting, .taskWhatsDue:
            return []
        case .captureParse:
            return ["text"]
        case .configSet:
            return ["key", "value"]
        case .notesAddLink, .taskAdd:
            return ["project", "text"]
        case .notesGet, .projectArchive, .projectFocus, .projectGet, .projectSetPartOf, .projectUnarchive, .sessionStart, .taskComplete, .taskDelete, .taskDiveIn, .taskDrop, .taskReopen, .taskSetDue, .taskSetWaiting:
            return ["project"]
        case .notesSetDetail:
            return ["key", "project", "value"]
        case .projectAdopt:
            return ["folder"]
        case .projectCreate:
            return ["title"]
        case .projectRename:
            return ["project", "title"]
        case .sessionDelete:
            return ["project", "session"]
        case .sessionNote:
            return ["project", "prose"]
        case .sessionRename:
            return ["label", "project", "session"]
        case .taskFocus, .taskUnwrap:
            return ["project", "task"]
        case .taskSearch:
            return ["query"]
        case .taskSetText, .taskWrap:
            return ["project", "task", "text"]
        }
    }

    /// Groups of fields of which exactly one must be given — `task` or `tasks` for the actions
    /// that take either, `due` or `clearDue` for the one that both sets and clears.
    var exclusiveGroups: [[String]] {
        switch self {
        case .appOpenInFinder, .appOpenInObsidian, .appOpenPageAsNewCard, .appOpenWindow, .appSettings, .appShowPanel, .captureParse, .configGet, .configSet, .focusGet, .journalList, .journalUndo, .notesAddLink, .notesGet, .notesSetDetail, .projectAdopt, .projectAdoptable, .projectArchive, .projectCreate, .projectFocus, .projectGet, .projectList, .projectRename, .projectSetPartOf, .projectUnarchive, .sessionDelete, .sessionNote, .sessionRename, .sessionStart, .taskAdd, .taskDiveIn, .taskDone, .taskFocus, .taskList, .taskProgress, .taskSearch, .taskSetText, .taskUnwrap, .taskWaiting, .taskWhatsDue, .taskWrap:
            return []
        case .taskComplete, .taskDelete, .taskDrop, .taskReopen:
            return [["task", "tasks"]]
        case .taskSetDue:
            return [["task", "tasks"], ["due", "clearDue"]]
        case .taskSetWaiting:
            return [["task", "tasks"], ["waiting", "clearWaiting"]]
        }
    }
}
